// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmq1sYvRKkrsJybbkbly9eftRB6ADcMec',
    appId: '1:536747204462:web:5c6ed10a924b4a40d62b7f',
    messagingSenderId: '536747204462',
    projectId: 'mjolnir-38c88',
    authDomain: 'mjolnir-38c88.firebaseapp.com',
    storageBucket: 'mjolnir-38c88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2srvEjOVf-roU4e287JeqKKOPUw5z9_8',
    appId: '1:536747204462:android:69852092d35f10cad62b7f',
    messagingSenderId: '536747204462',
    projectId: 'mjolnir-38c88',
    storageBucket: 'mjolnir-38c88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxtC-YQr_Vk7rnEdzHYNEAuHGp90s8n2Q',
    appId: '1:536747204462:ios:4df683c25cc72628d62b7f',
    messagingSenderId: '536747204462',
    projectId: 'mjolnir-38c88',
    storageBucket: 'mjolnir-38c88.firebasestorage.app',
    iosBundleId: 'com.example.mjolnir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxtC-YQr_Vk7rnEdzHYNEAuHGp90s8n2Q',
    appId: '1:536747204462:ios:4df683c25cc72628d62b7f',
    messagingSenderId: '536747204462',
    projectId: 'mjolnir-38c88',
    storageBucket: 'mjolnir-38c88.firebasestorage.app',
    iosBundleId: 'com.example.mjolnir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmq1sYvRKkrsJybbkbly9eftRB6ADcMec',
    appId: '1:536747204462:web:f208cc403689d978d62b7f',
    messagingSenderId: '536747204462',
    projectId: 'mjolnir-38c88',
    authDomain: 'mjolnir-38c88.firebaseapp.com',
    storageBucket: 'mjolnir-38c88.firebasestorage.app',
  );
}
